### ISSUE TITLE
使用教程

### ISSUE THREAD

**Issue by 775190041** [1Zxuan/mybatis-multi-datasource-spring-boot-starter#1]
发个使用教程可以嘛

**Comment by 1Zxuan** [comment]
https://github.com/1Zxuan/mybatis-multi-datasource-demo

**Comment by 1Zxuan** [comment]
> 发个使用教程可以嘛

https://github.com/1Zxuan/mybatis-multi-datasource-demo

**Comment by 775190041** [comment]
不能下载此依赖&nbsp;
<dependency&gt;
    <groupId&gt;com.louzx</groupId&gt;
    <artifactId&gt;mybatis-multi-datasource-spring-boot-starter</artifactId&gt;
    <version&gt;1.0.0</version&gt;
</dependency&gt;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "1Zxuan/mybatis-multi-datasource-spring-boot-starter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月6日(星期四) 上午10:35
***@***.***&gt;;
抄送:&nbsp;"疯子𖠚 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [1Zxuan/mybatis-multi-datasource-spring-boot-starter] 使用教程 (#1)





  
发个使用教程可以嘛
  
https://github.com/1Zxuan/mybatis-multi-datasource-demo

**Comment by 775190041** [comment]
移植到别的项目可以啦，谢谢高手




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "疯子𖠚 ᐝ"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月6日(星期四) 上午10:58
***@***.***&gt;;

主题:&nbsp;回复： [1Zxuan/mybatis-multi-datasource-spring-boot-starter] 使用教程 (#1)



不能下载此依赖 
<dependency&gt;
    <groupId&gt;com.louzx</groupId&gt;
    <artifactId&gt;mybatis-multi-datasource-spring-boot-starter</artifactId&gt;
    <version&gt;1.0.0</version&gt;
</dependency&gt;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "1Zxuan/mybatis-multi-datasource-spring-boot-starter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月6日(星期四) 上午10:35
***@***.***&gt;;
抄送:&nbsp;"疯子𖠚 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [1Zxuan/mybatis-multi-datasource-spring-boot-starter] 使用教程 (#1)





  
发个使用教程可以嘛
  
https://github.com/1Zxuan/mybatis-multi-datasource-demo

**Comment by 775190041** [comment]
谢谢大佬，不过遇到一点点问题，有url,但运行项目时提示我没有指定url。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "1Zxuan/mybatis-multi-datasource-spring-boot-starter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月6日(星期四) 下午5:12
***@***.***&gt;;
抄送:&nbsp;"疯子𖠚 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [1Zxuan/mybatis-multi-datasource-spring-boot-starter] 使用教程 (#1)





 
Closed #1.

**Comment by 1Zxuan** [comment]
> 谢谢大佬，不过遇到一点点问题，有url,但运行项目时提示我没有指定url。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "1Zxuan/mybatis-multi-datasource-spring-boot-starter" ***@***.***&gt;; 发送时间:&nbsp;2021年5月6日(星期四) 下午5:12 ***@***.***&gt;; 抄送:&nbsp;"疯子𖠚 ***@***.******@***.***&gt;; 主题:&nbsp;Re: [1Zxuan/mybatis-multi-datasource-spring-boot-starter] 使用教程 (#1) Closed #1. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

贴一下报错信息

**Comment by 775190041** [comment]
启动时错误：
Description:


Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.


Reason: Failed to determine a suitable driver class




Action:


Consider the following:
	If you want an embedded database (H2, HSQL or Derby), please put it on the classpath.
	If you have database settings to be loaded from a particular profile you may need to activate it (no profiles are currently active).






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "1Zxuan/mybatis-multi-datasource-spring-boot-starter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月6日(星期四) 下午5:37
***@***.***&gt;;
抄送:&nbsp;"疯子𖠚 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [1Zxuan/mybatis-multi-datasource-spring-boot-starter] 使用教程 (#1)





  
谢谢大佬，不过遇到一点点问题，有url,但运行项目时提示我没有指定url。
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "1Zxuan/mybatis-multi-datasource-spring-boot-starter" @.&gt;; 发送时间:&nbsp;2021年5月6日(星期四) 下午5:12 @.&gt;; 抄送:&nbsp;"疯子𖠚 @.@.&gt;; 主题:&nbsp;Re: [1Zxuan/mybatis-multi-datasource-spring-boot-starter] 使用教程 (#1) Closed #1. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
贴一下报错信息

**Comment by 1Zxuan** [comment]
> 启动时错误： Description: Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured. Reason: Failed to determine a suitable driver class Action: Consider the following: If you want an embedded database (H2, HSQL or Derby), please put it on the classpath. If you have database settings to be loaded from a particular profile you may need to activate it (no profiles are currently active).
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "1Zxuan/mybatis-multi-datasource-spring-boot-starter" ***@***.***&gt;; 发送时间:&nbsp;2021年5月6日(星期四) 下午5:37 ***@***.***&gt;; 抄送:&nbsp;"疯子𖠚 ***@***.******@***.***&gt;; 主题:&nbsp;Re: [1Zxuan/mybatis-multi-datasource-spring-boot-starter] 使用教程 (#1) 谢谢大佬，不过遇到一点点问题，有url,但运行项目时提示我没有指定url。 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "1Zxuan/mybatis-multi-datasource-spring-boot-starter" @.&gt;; 发送时间:&nbsp;2021年5月6日(星期四) 下午5:12 @.&gt;; 抄送:&nbsp;"疯子𖠚 @.@.&gt;; 主题:&nbsp;Re: [1Zxuan/mybatis-multi-datasource-spring-boot-starter] 使用教程 (#1) Closed #1. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. 贴一下报错信息 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

@SpringBootApplication(exclude = {DataSourceAutoConfiguration.class}) 试试看排除DataSourceAutoConfiguration.class

**Comment by 775190041** [comment]
==========随后我根据它的提示我在此DataSourceRouting类上加了@Component




========再启动时就遇见之前一致困扰我的问题，（无奈只能问大神您要教程了）

错误为：
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSourceAop': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSourceRouting' defined in file [D:\my\Java\mybatis-multi-datasource-spring-boot-starter\target\classes\com\louzx\multidatasource\core\DataSourceRouting.class]: Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: Property 'targetDataSources' is required





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "1Zxuan/mybatis-multi-datasource-spring-boot-starter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月6日(星期四) 下午5:43
***@***.***&gt;;
抄送:&nbsp;"疯子𖠚 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [1Zxuan/mybatis-multi-datasource-spring-boot-starter] 使用教程 (#1)





  
启动时错误： Description: Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured. Reason: Failed to determine a suitable driver class Action: Consider the following: If you want an embedded database (H2, HSQL or Derby), please put it on the classpath. If you have database settings to be loaded from a particular profile you may need to activate it (no profiles are currently active).
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "1Zxuan/mybatis-multi-datasource-spring-boot-starter" @.&gt;; 发送时间:&nbsp;2021年5月6日(星期四) 下午5:37 @.&gt;; 抄送:&nbsp;"疯子𖠚 @.@.&gt;; 主题:&nbsp;Re: [1Zxuan/mybatis-multi-datasource-spring-boot-starter] 使用教程 (#1) 谢谢大佬，不过遇到一点点问题，有url,但运行项目时提示我没有指定url。 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "1Zxuan/mybatis-multi-datasource-spring-boot-starter" @.&gt;; 发送时间:&nbsp;2021年5月6日(星期四) 下午5:12 @.&gt;; 抄送:&nbsp;"疯子𖠚 @.@.&gt;; 主题:&nbsp;Re: [1Zxuan/mybatis-multi-datasource-spring-boot-starter] 使用教程 (#1) Closed #1. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. 贴一下报错信息 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
@SpringBootApplication(exclude = {DataSourceAutoConfiguration.class}) 试试看排除DataSourceAutoConfiguration.class

**Comment by 775190041** [comment]
&nbsp;看了一个通宵都没有解决这个问题。


org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSourceAop': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSourceRouting' defined in file [D:\my\Java\mybatis-multi-datasource-spring-boot-starter\target\classes\com\louzx\multidatasource\core\DataSourceRouting.class]: Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: Property 'targetDataSources' is required







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "1Zxuan/mybatis-multi-datasource-spring-boot-starter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月6日(星期四) 下午5:43
***@***.***&gt;;
抄送:&nbsp;"疯子𖠚 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [1Zxuan/mybatis-multi-datasource-spring-boot-starter] 使用教程 (#1)





  
启动时错误： Description: Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured. Reason: Failed to determine a suitable driver class Action: Consider the following: If you want an embedded database (H2, HSQL or Derby), please put it on the classpath. If you have database settings to be loaded from a particular profile you may need to activate it (no profiles are currently active).
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "1Zxuan/mybatis-multi-datasource-spring-boot-starter" @.&gt;; 发送时间:&nbsp;2021年5月6日(星期四) 下午5:37 @.&gt;; 抄送:&nbsp;"疯子𖠚 @.@.&gt;; 主题:&nbsp;Re: [1Zxuan/mybatis-multi-datasource-spring-boot-starter] 使用教程 (#1) 谢谢大佬，不过遇到一点点问题，有url,但运行项目时提示我没有指定url。 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "1Zxuan/mybatis-multi-datasource-spring-boot-starter" @.&gt;; 发送时间:&nbsp;2021年5月6日(星期四) 下午5:12 @.&gt;; 抄送:&nbsp;"疯子𖠚 @.@.&gt;; 主题:&nbsp;Re: [1Zxuan/mybatis-multi-datasource-spring-boot-starter] 使用教程 (#1) Closed #1. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. 贴一下报错信息 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
@SpringBootApplication(exclude = {DataSourceAutoConfiguration.class}) 试试看排除DataSourceAutoConfiguration.class

**Comment by 1Zxuan** [comment]
> &nbsp;看了一个通宵都没有解决这个问题。 org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSourceAop': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSourceRouting' defined in file [D:\my\Java\mybatis-multi-datasource-spring-boot-starter\target\classes\com\louzx\multidatasource\core\DataSourceRouting.class]: Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: Property 'targetDataSources' is required
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "1Zxuan/mybatis-multi-datasource-spring-boot-starter" ***@***.***&gt;; 发送时间:&nbsp;2021年5月6日(星期四) 下午5:43 ***@***.***&gt;; 抄送:&nbsp;"疯子𖠚 ***@***.******@***.***&gt;; 主题:&nbsp;Re: [1Zxuan/mybatis-multi-datasource-spring-boot-starter] 使用教程 (#1) 启动时错误： Description: Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured. Reason: Failed to determine a suitable driver class Action: Consider the following: If you want an embedded database (H2, HSQL or Derby), please put it on the classpath. If you have database settings to be loaded from a particular profile you may need to activate it (no profiles are currently active). … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "1Zxuan/mybatis-multi-datasource-spring-boot-starter" @.&gt;; 发送时间:&nbsp;2021年5月6日(星期四) 下午5:37 @.&gt;; 抄送:&nbsp;"疯子𖠚 @.@.&gt;; 主题:&nbsp;Re: [1Zxuan/mybatis-multi-datasource-spring-boot-starter] 使用教程 (#1) 谢谢大佬，不过遇到一点点问题，有url,但运行项目时提示我没有指定url。 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "1Zxuan/mybatis-multi-datasource-spring-boot-starter" @.&gt;; 发送时间:&nbsp;2021年5月6日(星期四) 下午5:12 @.&gt;; 抄送:&nbsp;"疯子𖠚 @.@.&gt;; 主题:&nbsp;Re: [1Zxuan/mybatis-multi-datasource-spring-boot-starter] 使用教程 (#1) Closed #1. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. 贴一下报错信息 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. @SpringBootApplication(exclude = {DataSourceAutoConfiguration.class}) 试试看排除DataSourceAutoConfiguration.class — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

方便贴项目代码吗，或者给我你的QQ联系方式

**Comment by 775190041** [comment]
QQ联系我吧，我把代码发你
775190041




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "1Zxuan/mybatis-multi-datasource-spring-boot-starter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月6日(星期四) 晚上6:17
***@***.***&gt;;
抄送:&nbsp;"疯子𖠚 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [1Zxuan/mybatis-multi-datasource-spring-boot-starter] 使用教程 (#1)





  
&nbsp;看了一个通宵都没有解决这个问题。 org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSourceAop': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSourceRouting' defined in file [D:\my\Java\mybatis-multi-datasource-spring-boot-starter\target\classes\com\louzx\multidatasource\core\DataSourceRouting.class]: Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: Property 'targetDataSources' is required
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "1Zxuan/mybatis-multi-datasource-spring-boot-starter" @.&gt;; 发送时间:&nbsp;2021年5月6日(星期四) 下午5:43 @.&gt;; 抄送:&nbsp;"疯子𖠚 @.@.&gt;; 主题:&nbsp;Re: [1Zxuan/mybatis-multi-datasource-spring-boot-starter] 使用教程 (#1) 启动时错误： Description: Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured. Reason: Failed to determine a suitable driver class Action: Consider the following: If you want an embedded database (H2, HSQL or Derby), please put it on the classpath. If you have database settings to be loaded from a particular profile you may need to activate it (no profiles are currently active). … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "1Zxuan/mybatis-multi-datasource-spring-boot-starter" @.&gt;; 发送时间:&nbsp;2021年5月6日(星期四) 下午5:37 @.&gt;; 抄送:&nbsp;"疯子𖠚 @.@.&gt;; 主题:&nbsp;Re: [1Zxuan/mybatis-multi-datasource-spring-boot-starter] 使用教程 (#1) 谢谢大佬，不过遇到一点点问题，有url,但运行项目时提示我没有指定url。 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "1Zxuan/mybatis-multi-datasource-spring-boot-starter" @.&gt;; 发送时间:&nbsp;2021年5月6日(星期四) 下午5:12 @.&gt;; 抄送:&nbsp;"疯子𖠚 @.@.&gt;; 主题:&nbsp;Re: [1Zxuan/mybatis-multi-datasource-spring-boot-starter] 使用教程 (#1) Closed #1. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. 贴一下报错信息 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. @SpringBootApplication(exclude = {DataSourceAutoConfiguration.class}) 试试看排除DataSourceAutoConfiguration.class — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
方便贴项目代码吗，或者给我你的QQ联系方式
